[package]

name = "astro"
version = "1.0.3"
authors = ["Saurav Sachidanand"]

license = "MIT"

repository = "https://www.github.com/saurvs/astro-rust"
homepage = "https://saurvs.github.io/astro-rust"

description = " Algorithms for accurate astronomy. An MIT licensed library of astronomical algorithms for the Rust programming language."
keywords = ["astronomy", "algorithms", "ephemeris", "planet", "solar"]
