[package]

name = "astro"
version = "0.0.8"
authors = ["Saurav Sachidanand"]

license = "MIT"

repository = "https://www.github.com/saurvs/astro-rust"
homepage = "https://saurvs.github.io/astro-rust"

description = "Algorithms made for rigorous and accurate astronomical calculations."
keywords = ["astro", "astronomy", "algorithms", "ephemeris", "planets", "solar", "star", "moon"]
