[package]

name = "astro_rust"
version = "0.0.4"
authors = ["Saurav Sachidanand"]
description = "Algorithms written in Rust, for finding/calculating/estimating things that are of interest in astronomy."
keywords = ["astronomy", "algorithms", "ephemeris", "planets", "solar"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/qpid/astro-rust"
homepage = "https://github.com/qpid/astro-rust"
