[package]

name = "rusty-astronomy"
version = "0.0.3"
authors = ["Saurav Sachidanand"]
description = "Highly accurate and efficient astronomical algorithms, written in Rust, for calculating interesting things about bodies in our solar system."
keywords = ["astronomy", "algorithms", "ephemeris", "planets", "solar"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/qpid/rusty-astronomy"
homepage = "https://github.com/qpid/rusty-astronomy"
